source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StackView_Example' do
  pod "StackViewComponent", :path => "../"
end

target 'StackView_Tests' do
  pod "StackViewComponent", :path => "../"

end
