source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StackView_Example', :exclusive => true do
  pod "StackViewComponent", :path => "../"
end

target 'StackView_Tests', :exclusive => true do
  pod "StackViewComponent", :path => "../"

end
